Add mobile menu
dhy-612/Resume pull request #11
Opened 2023-03-07 17:19 UTC by dhy-612

New Milestone completed
In mobile, implemented the following features:
- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2023-03-07 17:33 UTC, Gambit142 reviewed
Hi @dhy-612 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- This is a pair-programming exercise but you are the only one that contributed to the success of this project. Kindly collaborate with your partner. 👍 😎

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-07 20:09 UTC, huseyinbiyik commented
Hi team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

🔴 You have submitted a project, that has no Eslint linter setup. Since we start to use JavaScript for this project, now we need to set up HTML&CSS&JavaScript linters. Kindly check the project requirements.
<img width="817" alt="Screenshot 2023-03-07 at 11 08 12 PM" src="https://user-images.githubusercontent.com/25887253/223540666-3781e6a7-c4e9-4e64-8d41-4532b6d2255d.png">



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-07 20:39 UTC, osamaashraf6 reviewed
Hi @dhy-612 😊, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🆘💀

🔴 You have submitted a project, that has no Eslint linter setup. Since we start to use JavaScript for this project, now we need to set up HTML&CSS&JavaScript linters. Kindly check the project requirements.
https://user-images.githubusercontent.com/25887253/223540666-3781e6a7-c4e9-4e64-8d41-4532b6d2255d.png


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-07 21:42 UTC, franclobo requested changes
Hi @dhy-612 and @J-C-S-V, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/223558428-fe558261-9aa8-44e5-9dc1-bed125a599d3.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Professional README file ✔️ 
- Good use of querrySelector method ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 21:42 UTC, franclobo commented on index.html
> +                    <li><a class="menuItem" href="#contact">Contacts</a></li>
- [ ] Well done declaring the `href` but there isn't the correspondent `id` for each section, I mean for the `href="#About"` there should be an `id="About"` near the About section. Please 🙏🏽 add the id on each section to make it possible to navigate to the correspndant section when the user click on the links for a better user experience.

2023-03-07 21:42 UTC, franclobo commented on style.css
> +}
- [ ] Please 🙏🏽 avoid using `important` for the best practices f HTML & CSS.
- [ ] When the user scrolls up the close icon moves, please 🙏🏽 fix it for a better user experience.

2023-03-07 21:51 UTC, dhy-612 commented on style.css
> +}
> * [x]  Please 🙏🏽 avoid using `important` for the best practices f HTML & CSS.
> * [ ]  When the user scrolls up the close icon moves, please 🙏🏽 fix it for a better user experience.
@franclobo I have also faced the same issue of moving icons but it is due to zoom in or zoom of the screen

2023-03-07 22:24 UTC, huseyinbiyik requested changes
Hi team,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Cool menu animation 😎 
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- PR description is descriptive 📝


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 22:24 UTC, huseyinbiyik commented on index.html
>        <section class="About-container">
As the previous requested, you added the link to the navigation like href="#About", but also you need to add id="About" to this line to make it work. Also please add id to Profile and Contacts.

2023-03-07 22:24 UTC, huseyinbiyik commented on style.css
> +.closeIcon {
Kindly fix the issue with the close button as the previous reviewer requested. You can lock the screen to prevent flowing or fix the position of close button.
![l](https://user-images.githubusercontent.com/25887253/223567035-a8a9e8b9-1208-43f3-abcb-659a192cddc5.gif)

2023-03-08 00:27 UTC, Munsa1 requested changes
Hi @dhy-612, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Added `id's` to the menu links as requested just not in the right places :heavy_check_mark: 
Fixed the close button positioning issue as requested :heavy_check_mark:  

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 00:27 UTC, Munsa1 commented on index.html
>        <section class="About-container">
- [ ] As requested here, kindly add corresponding `id` tags to your `html` code so as to take the user to the part of the page clicked on by the menu link. This means when the user clicks on the `contact` link, the menu should close and take the user to the `contact` section of the page. And when the user clicks on the `about` link, the menu should close and take the user to the `about` section of the page. Lastly, this should be done for the `portfolio` link as well.

for example
Remove the `id="about"` from line `23` and add it here in line `164`
![image](https://user-images.githubusercontent.com/81932478/223585705-4394ee52-c47c-4a1e-9459-8a5f14c7aebd.png)

Also, remove `id="contact"` from the line `24` and add it to line `224`
![image](https://user-images.githubusercontent.com/81932478/223586016-67343712-7065-470c-b3a7-bd248cdfa672.png)

Lastly, remove `id="profile"` from line `22` and add it to line `74`
![image](https://user-images.githubusercontent.com/81932478/223586334-55d0d9c7-2b13-4378-84e0-49edc9561995.png)

- [ ] Finally fix your javascript code so that when the user clicks the menu links, the corresponding part of the page comes into view

2023-03-08 13:11 UTC, didierganthier approved these changes
Hi Team,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/l9CSJHK88kMTe/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Menu working ✔️ 
- Correct GitHub flow ✔️ 

## Optional Suggestions 💡
- [x] Well done overall 💯 however the linters aren't configured quite well yet, you're using the `HTML + CSS` when you should've been using the [HTML + CSS + JS Linters](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) considering that your project contains `JS` code. This is optional as it was not mentioned by the previous reviewer 😅  but I strongly encourage you to update your `linters.yml` file with that one [here](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) to ensure that you have all the linters check. ✅ 

- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-03-08 13:57 UTC, merged